version: '3'

services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
  src:
    build:
      context: ./timer-app
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    links:
      - "server:be"